name: Tests Continus

on:
  push:
    branches:
      - main  # la branche à surveiller

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
  notifications:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification
        uses: rtCamp/action-slack-notify@v2
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,workflow,job,took
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}